Repository neo4j-contrib/spatial, pull requests merged in 2025-04, with the labels that each got.

#435 Refactor JsonMapper for improved property sorting and serialization for docs
  src/test/java/org/neo4j/doc/domain/examples/Mapper.java
Labels: doc

#395 Minor version updates and code polishes
  .github/actions/setup-jdk/action.yaml
  docs/docs/modules/ROOT/images/generated/buffer.png
  docs/docs/modules/ROOT/images/generated/convex_hull.png
  docs/docs/modules/ROOT/images/generated/end_point.png
  docs/docs/modules/ROOT/images/generated/envelope.png
  docs/docs/modules/ROOT/images/generated/layers/concaveLayer.png
  docs/docs/modules/ROOT/images/generated/layers/linesLayer.png
  docs/docs/modules/ROOT/images/generated/layers/osmLayer.png
  docs/docs/modules/ROOT/images/generated/start_point.png
  docs/docs/modules/ROOT/images/generated/step1_break_up_all_geometries_into_points_and_make_density_islands.png
  docs/docs/modules/ROOT/images/generated/step3_break_up_all_geometries_into_points_and_make_density_islands.png
  docs/docs/modules/ROOT/images/generated/step4_break_up_all_geometries_into_points_and_make_density_islands.png
  docs/docs/modules/ROOT/images/generated/step5_break_up_all_geometries_into_points_and_make_density_islands.png
  pom.xml
  src/main/java/org/geotools/data/neo4j/Neo4jSpatialDataStore.java
  src/main/java/org/neo4j/gis/spatial/DynamicLayerConfig.java
  src/main/java/org/neo4j/gis/spatial/SpatialDatabaseRecord.java
  src/main/java/org/neo4j/gis/spatial/SpatialDatabaseService.java
  src/main/java/org/neo4j/gis/spatial/WKBGeometryEncoder.java
  src/main/java/org/neo4j/gis/spatial/WKTGeometryEncoder.java
  src/main/java/org/neo4j/gis/spatial/attributes/PropertyMapper.java
  src/main/java/org/neo4j/gis/spatial/attributes/PropertyMappingManager.java
  src/main/java/org/neo4j/gis/spatial/filter/SearchCQL.java
  src/main/java/org/neo4j/gis/spatial/index/IndexManager.java
  src/main/java/org/neo4j/gis/spatial/index/LayerSpaceFillingCurvePointIndex.java
  src/main/java/org/neo4j/gis/spatial/osm/OSMImporter.java
  src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java
  src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java
  src/test/java/org/neo4j/gis/spatial/RTreeBulkInsertTest.java
Labels: dependencies, refactoring

#438 Remove obsolete build and documentation configurations
  .github/actions/setup-jdk/action.yaml
  Makefile
  osgi.bnd
  pom.xml
  src/main/assembly/docs-assembly.xml
Labels: dependencies
